# Generated by Django 3.2.12 on 2022-04-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mod', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='ModInfo',
        ),
    ]
