# Generated by Django 3.2.12 on 2022-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mod', '0002_rename_test_modinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modinfo',
            name='ident',
            field=models.CharField(default='model0', max_length=20),
            preserve_default=False,
        ),
    ]
