# Generated by Django 3.2.12 on 2022-04-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mod', '0005_modinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='modinfo',
            name='add',
            field=models.CharField(default='root', max_length=1000),
            preserve_default=False,
        ),
    ]
