# Generated by Django 3.2.12 on 2022-04-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mod', '0006_modinfo_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='modinfo',
            name='test',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
