# Generated by Django 4.0.4 on 2022-04-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=20)),
                ('modelid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accur', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
