# Generated by Django 3.2.12 on 2022-04-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mod', '0003_modinfo_ident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modinfo',
            name='ident',
        ),
    ]
