# Generated by Django 3.2.12 on 2022-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mod', '0004_remove_modinfo_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='modinfo',
            name='owner',
            field=models.CharField(default='root', max_length=10),
            preserve_default=False,
        ),
    ]
